### PR TITLE
Branch sorting bug

### LINKED ISSUE #123: Editing remark field sometimes changes the order of the person within the addressbook

### PR DESCRIPTION
**Pull request by IanCheah**
Fixes #123

### CODE REVIEW

File: src/main/java/seedu/address/model/person/PriorityHighToLowComparator.java [hunk 1]
```diff
@@ -9,7 +9,14 @@ public class PriorityHighToLowComparator implements Comparator<Person> {
...
     public int compare(Person o1, Person o2) {
-        return o1.getPriority().compareTo(o2.getPriority());
+        int comparisonResult = o1.getPriority().compareTo(o2.getPriority());
+
+        if (comparisonResult != 0) {
+            return comparisonResult;
+        }
+
+        // If same priority, compare by name for tie-breaker
+        return o1.getName().compareTo(o2.getName());
```
Comment (justsparsh) [inline src/main/java/seedu/address/model/person/PriorityHighToLowComparator.java:19]: Good job on catching this edge case

**Review by justsparsh — APPROVED** [review]
